//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workshop()
        {
            this.Materials = new HashSet<Material>();
            this.ParticipantWorkshops = new HashSet<ParticipantWorkshop>();
            this.TrainerWorkshops = new HashSet<TrainerWorkshop>();
        }
    
        public int WorkshopId { get; set; }
        public string WorkshopTitle { get; set; }
        public Nullable<System.DateTime> WorkshopDate { get; set; }
        public string WorkshopTime { get; set; }
        public Nullable<double> WorkshopDuration { get; set; }
        public Nullable<int> WorkshopSeats { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantWorkshop> ParticipantWorkshops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerWorkshop> TrainerWorkshops { get; set; }
    }
}
